### ISSUE TITLE
Doesn't compile with GCC 8.1.0

### ISSUE THREAD

**Issue by neongreen** [wireapp/wire-server#320]
```
src/http/ngx_http_script.c: In function ‘ngx_http_script_add_full_name_code’:
src/http/ngx_http_script.c:1296:18: error: cast between incompatible function types from ‘size_t (*)(ngx_http_script_engine_t *)’ {aka ‘long unsigned int (*)(struct <anonymous> *)’} to ‘void (*)(ngx_http_script_engine_t *)’ {aka ‘void (*)(struct <anonymous> *)’} [-Werror=cast-function-type]
     code->code = (ngx_http_script_code_pt) ngx_http_script_full_name_len_code;
                  ^
cc1: all warnings being treated as errors
make[3]: *** [objs/Makefile:947: objs/src/http/ngx_http_script.o] Error 1
make[3]: Leaving directory '/home/yom/wire/server/services/nginz/src'```

**Comment by neongreen** [comment]
Fixed here: https://trac.nginx.org/nginx/ticket/1546

**Comment by neongreen** [comment]
The fix is not in any release yet (and we're stuck on 1.12 anyway) so I'll make a custom patch.
